name: test-build

on:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.arch }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: arm64
            tool: aarch64-unknown-linux-musl
          - arch: arm
            tool: armv7-unknown-linux-musleabi
          - arch: armhf
            tool: armv7-unknown-linux-musleabihf
          - arch: loong64
            tool: loongarch64-unknown-linux-musl
          - arch: m68k
            tool: m68k-unknown-linux-musl
          - arch: mips64el
            tool: mips64el-unknown-linux-musl
          - arch: mips64
            tool: mips64-unknown-linux-musl
          - arch: mipsel
            tool: mipsel-unknown-linux-musl
          - arch: mipselsf
            tool: mipsel-unknown-linux-muslsf
          - arch: mips
            tool: mips-unknown-linux-musl
          - arch: mipssf
            tool: mips-unknown-linux-muslsf
          - arch: powerpc64
            tool: powerpc64-unknown-linux-musl
          - arch: powerpc
            tool: powerpc-unknown-linux-musl
          - arch: riscv
            tool: riscv32-unknown-linux-musl
          - arch: riscv64
            tool: riscv64-unknown-linux-musl
          - arch: s390x
            tool: s390x-ibm-linux-musl
          - arch: sh4
            tool: sh4-multilib-linux-musl
          - arch: x86
            tool: i686-unknown-linux-musl
          - arch: x86-64
            tool: x86_64-unknown-linux-musl
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Checkout 7-Zip sources
        uses: actions/checkout@v6
        with:
          repository: 'gfunkmonk/7zip'
          path: 7zip

      - name: Set up build tools
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: 'gfunkmonk/musl-cross'
          TOOL: ${{ matrix.tool }}
        run: |
          echo "deb [trusted=yes] http://ppa.launchpad.net/far2l-team/tools/ubuntu bionic main" | sudo tee /etc/apt/sources.list.d/tools.list
          sudo apt update -qq && sudo apt install -y dos2unix quilt uasm upx-ucl
          TAG=$(gh api repos/$REPO/releases/latest --jq '.tag_name')
          echo "TAG:["$TAG"]"
          mkdir -p $HOME/x-tools
          echo "tools:[" "https://github.com/$REPO/releases/download/$TAG/$TOOL" "]"
          pushd $HOME/x-tools
          wget https://github.com/$REPO/releases/download/$TAG/$TOOL.tar.xz
          tar xvf $TOOL.tar.xz
          popd
          [ -d "$HOME/x-tools/$TOOL/bin" ] && echo "$HOME/x-tools/$TOOL/bin" >> $GITHUB_PATH

      - name: Build 7-Zip [${{ matrix.arch }}]
        id: build
        env:
          ARCH: ${{ matrix.arch }}
          TOOL: ${{ matrix.tool }}
        working-directory: 7zip
        run: |
          bash ../build_7zip.sh

      - name: Upload artifacts
        if: steps.build.outcome == 'success'
        uses: actions/upload-artifact@v7
        with:
          name: 7zz-${{ matrix.arch }}
          path: ./**/7zz-*.tar*

  build-macos:
    name: macos-${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86-64
            runner: macos-15-intel
          - arch: arm64
            runner: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Checkout 7-Zip sources
        uses: actions/checkout@v6
        with:
          repository: 'gfunkmonk/7zip'
          path: 7zip

      - name: Set up build tools
        run: |
          brew install dos2unix quilt

      - name: Build 7-Zip [macos-${{ matrix.arch }}]
        id: build
        env:
          ARCH: ${{ matrix.arch }}
          PLATFORM: macOS
        working-directory: 7zip
        run: |
          bash ../build_7zip.sh

      - name: Upload artifacts
        if: steps.build.outcome == 'success'
        uses: actions/upload-artifact@v7
        with:
          name: 7zz-macos-${{ matrix.arch }}
          path: ./**/7zz-*.tar*

  macos-universal:
    needs:
      - build-macos
    runs-on: macos-latest
    steps:
      - uses: actions/download-artifact@v8
        with:
          path: artifacts
      - name: Extract binaries
        run: |
          tar -xJf artifacts/7zz-macos-arm64/*.tar.xz -C artifacts/7zz-macos-arm64/
          tar -xJf artifacts/7zz-macos-x86-64/*.tar.xz -C artifacts/7zz-macos-x86-64/
      - name: run lipo to create universal binary
        run: lipo -create -arch arm64 artifacts/7zz-macos-arm64/7zz -arch x86_64 artifacts/7zz-macos-x86-64/7zz -output 7zz
      - name: tar xz binary
        run: |
          tar -cJvf 7zz-macOS-Universal.tar.xz 7zz
      - uses: actions/upload-artifact@v7
        with:
          name: 7zz-macOS-Universal
          path: 7zz-macOS-Universal.tar.xz

  release:
    needs: [build, build-macos, macos-universal]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8

      - name: Get release version
        env:
          REPO: 'ip7z/7zip'
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "VERSION=$(gh api repos/$REPO/releases/latest --jq '.tag_name')" >> $GITHUB_ENV

      - name: Delete Previous Release
        run: |
          gh release delete "${{ env.VERSION }}" --repo "${GITHUB_REPOSITORY}" --cleanup-tag -y || echo "No release to delete"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          prerelease: false
          tag_name: ${{ env.VERSION }}
          name: ${{ env.VERSION }}
          overwrite_files: true
          body: |
            ### 7-Zip ${{ env.VERSION }}
          files: |
            ./**/7zz-*.tar*
